FROM scratch
MAINTAINER Octoblu, Inc. <docker@octoblu.com>

ADD image-upload-to-dropbox-and-post-to-slack image-upload-to-dropbox-and-post-to-slack
ENTRYPOINT ["./image-upload-to-dropbox-and-post-to-slack"]
